name: flutter_khalti
description: A fluter plugin to process khalti payment
version: 1.1.0
author: Aawaz Gyawali <awazgyawali@gmail.com>
homepage: https://github.com/awazgyawali/flutter_khalti

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutterkhalti
    pluginClass: FlutterKhaltiPlugin
